### ISSUE TITLE
Restrict growth of harvester

### ISSUE THREAD

**Issue by cmeessen** [fatiando/fatiando#312]
To constrain thicknesses of surfaces with the harvester it would be handy to restrict the growth in an upward or downward direction.

@leouieda suggested to mask the prism mesh to prevent the harvester from expanding into unwanted directions.

**Comment by leouieda** [comment]
@cmeessen thanks for reporting this and for creating the PR!

**Comment by cmeessen** [comment]
The problem with masking the mesh is that the harvester still can grow sidewards. This in turn results in somewhat porous bodies that I would like to avoid. I had a closer look at `harvester.py` and came up with the following solution:

To `_neighbor_indexes()` I now hand over a list `restrict` with directions that restrict the growth. The list needs to be defined when calling `harvest()` and is empty by default. Here is a [link](https://github.com/fatiando/fatiando/compare/master...cmeessen:harvest-restricted) showing the changes in the code in my fork.

**Comment by leouieda** [comment]
@cmeessen OK, that really seems like a good solution! Would you open another PR with these changes?

One thing I saw right away: never use Python mutable objects (lists, dicts, numpy arrays) as default arguments. Specifically `restrict=[]`. The problem is that the list will be created when the module is imported. So every call to harvester will use the same list (in memory). If you do `restrict.append` or modify the list in any way, all calls to harvester will be affected. It's better to use `restrict=None` and check `if restrict is None` in the code to avoid this kind of thing.

**Comment by cmeessen** [comment]
@leouieda thank you for the input. I changed the code according to your comment and created the PR.

**Comment by leouieda** [comment]
@cmeessen great! I appologize in advance if I takes me some time to look carefully at the code. This month is a bit crazy for me.
