### ISSUE TITLE
Mayavi 4.5.0 doesn't downgrade Numpy

### ISSUE THREAD

**Issue by santis19** [fatiando/fatiando#418]
I've noticed that Mayavi 4.5.0 does not require Numpy 1.9:

```
$ conda info mayavi
[...]
mayavi 4.5.0 np111py27_2
------------------------
file name   : mayavi-4.5.0-np111py27_2.tar.bz2
name        : mayavi
version     : 4.5.0
build string: np111py27_2
build number: 2
channel     : conda-forge
size        : 12.6 MB
arch        : x86_64
has_prefix  : True
license     : BSD-3-Clause
license_family: BSD
md5         : 837ff3be356de81109cb5a0f2984394c
noarch      : None
platform    : linux
requires    : ()
subdir      : linux-64
url         : https://conda.anaconda.org/conda-forge/linux-64/mayavi-4.5.0-np111py27_2.tar.bz2
dependencies:
    apptools
    envisage
    numpy 1.11*
    pyqt 4.*
    python 2.7*
    setuptools
    traitsui
    vtk 7.1.*
[...]
```

So the warning that appears on [http://www.fatiando.org/install.html](http://www.fatiando.org/install.html) wouldn't be necessary.

Can we remove it? Or we need more tests in order to guarantee that everything works well with this new mayavi version?

**Comment by leouieda** [comment]
@santis19 the current test suite should be running against the updated versions of Mayavi and numpy. There doesn't seem to be an issue with it.

We can't really update that page until a new version is out (since it's all auto generated). We can fix it in master and it will appear once I release 0.6 (man, it's way overdue). 

Another thing that will have to be done is rebuild the conda recipes: https://github.com/conda-forge/fatiando-feedstock/blob/master/recipe/meta.yaml#L22

I'll get started on that it should be available for 0.5.

**Comment by leouieda** [comment]
@santis19 I'll report back if the conda packages are building without problems

**Comment by leouieda** [comment]
I started a PR to update the conda recipe. Just gotta wait until the CIs are done building it.

https://github.com/conda-forge/fatiando-feedstock/pull/9

**Comment by leouieda** [comment]
Done. Built packages should be available shortly.
